Repository DB-TermProject/twitter-term-project, pull requests merged in 2024-11, with the labels that each got.

#17 Refactor: validate request dto
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/misc.xml
  src/main/java/org/example/ui/page/ActionJLabel.java
  src/main/java/org/example/ui/page/FindPage.java
  src/main/java/org/example/ui/page/ImageJLabel.java
  src/main/java/org/example/ui/page/LoginPage.java
  src/main/java/org/example/ui/page/RoundJButton.java
  src/main/java/org/example/ui/page/RoundJPasswordField.java
  src/main/java/org/example/ui/page/RoundJTextField.java
  src/main/java/org/example/ui/page/SignUpPage.java
  src/main/resources/images/TwitterLogo.png
Labels: feature, client

#28 Feat/sign up UI
  src/main/java/org/example/TwitterApplication.java
  src/main/java/org/example/ui/page/SignUpPage.java
Labels: feature, client

#30 feat : my-page-ui
  src/main/java/org/example/ui/component/button/RoundButton.java
  src/main/java/org/example/ui/page/ChangePasswordPage.java
  src/main/java/org/example/ui/page/LoginPage.java
  src/main/java/org/example/ui/page/MyPage.java
  src/main/java/org/example/ui/page/TweetDetailPage.java
  src/main/java/org/example/ui/page/UpdateMemberInformationPage.java
Labels: feature, client

#31 Feat: detail-post-ui
  src/main/java/org/example/TwitterApplication.java
  src/main/java/org/example/ui/component/button/BackButton.java
  src/main/java/org/example/ui/component/field/TweetField.java
  src/main/java/org/example/ui/component/label/InteractionLabel.java
  src/main/java/org/example/ui/component/label/ProfileLabel.java
  src/main/java/org/example/ui/component/label/UserInfoLabel.java
  src/main/java/org/example/ui/component/panel/EmptyFeedPanel.java
  src/main/java/org/example/ui/component/panel/FeedPanel.java
  src/main/java/org/example/ui/component/panel/HeaderPanel.java
  src/main/java/org/example/ui/component/panel/InteractionPanel.java
  src/main/java/org/example/ui/component/panel/NavigationPanel.java
  src/main/java/org/example/ui/component/panel/TweetPanel.java
  src/main/java/org/example/ui/page/HomeFeedPage.java
  src/main/java/org/example/ui/page/HomeFeedPage_copy.java
  src/main/java/org/example/ui/page/TweetDetailPage.java
Labels: feature, client

#32 feat/follower-page-ui
  src/main/java/org/example/ui/page/FollowPage.java
Labels: feature, client

#35 Feat: comment domain api
  src/main/java/org/example/domain/comment/dto/CommentReqDTO.java
  src/main/java/org/example/domain/comment/dto/CommentResDTO.java
  src/main/java/org/example/domain/comment/repository/CommentRepository.java
  src/main/java/org/example/domain/comment/service/CommentService.java
  src/main/java/org/example/domain/post/repository/PostRepository.java
  src/main/java/org/example/domain/post/service/PostService.java
  src/main/java/org/example/domain/user/dto/UserReqDTO.java
  src/main/java/org/example/domain/user/service/UserService.java
  src/test/java/org/example/domain/comment/service/CommentServiceTest.java
Labels: feature, server

#37 Feat/like domain api
  .idea/sqldialects.xml
  src/main/java/org/example/domain/comment/repository/CommentRepository.java
  src/main/java/org/example/domain/comment/service/CommentService.java
  src/main/java/org/example/domain/like/repository/CommentLikeRepository.java
  src/main/java/org/example/domain/like/repository/LikeRepository.java
  src/main/java/org/example/domain/like/repository/PostLikeRepository.java
  src/main/java/org/example/domain/like/service/CommentLikeService.java
  src/main/java/org/example/domain/like/service/LikeService.java
  src/main/java/org/example/domain/like/service/PostLikeService.java
  src/main/java/org/example/domain/post/repository/PostRepository.java
  src/main/java/org/example/domain/post/service/PostService.java
  src/test/java/org/example/domain/like/service/CommentLikeServiceTest.java
  src/test/java/org/example/domain/post/service/PostServiceTest.java
Labels: feature, server

#42 Feat/like domain api
  .idea/sqldialects.xml
  src/main/java/org/example/domain/comment/dto/CommentResDTO.java
  src/main/java/org/example/domain/comment/repository/CommentRepository.java
  src/main/java/org/example/domain/comment/service/CommentService.java
  src/main/java/org/example/domain/follow/repository/FollowRepository.java
  src/main/java/org/example/domain/follow/service/FollowService.java
  src/main/java/org/example/domain/like/service/CommentLikeService.java
  src/main/java/org/example/domain/like/service/PostLikeService.java
  src/main/java/org/example/domain/notice/dto/NoticeResDTO.java
  src/main/java/org/example/domain/notice/enums/NoticeMessage.java
  src/main/java/org/example/domain/notice/repository/NoticeRepository.java
  src/main/java/org/example/domain/notice/service/NoticeService.java
  src/main/java/org/example/domain/post/dto/PostResDTO.java
  src/main/java/org/example/domain/post/repository/PostRepository.java
  src/main/java/org/example/domain/post/service/PostService.java
  src/main/java/org/example/domain/user/repository/UserRepository.java
  src/main/java/org/example/domain/user/service/UserService.java
  src/main/java/org/example/util/converter/TimeConverter.java
  src/test/java/org/example/domain/notice/service/NoticeServiceTest.java
Labels: feature, server

#45 Feat/write post update UI
  .idea/dataSources.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/sqldialects.xml
  src/main/java/org/example/TwitterApplication.java
  src/main/java/org/example/asset/send.png
  src/main/java/org/example/ui/component/field/TweetField.java
  src/main/java/org/example/ui/component/label/InteractionLabel.java
  src/main/java/org/example/ui/component/panel/FeedPanel.java
  src/main/java/org/example/ui/component/panel/InteractionPanel.java
  src/main/java/org/example/ui/component/panel/MyPageMainPanel.java
  src/main/java/org/example/ui/component/panel/TweetPanel.java
  src/main/java/org/example/ui/page/HomeFeedPage.java
  src/main/java/org/example/ui/page/HomeFeedPage_copy.java
  src/main/java/org/example/ui/page/NewTweetPage.java
  src/main/java/org/example/ui/page/TweetDetailPage.java
Labels: enhancement, feature

#50 feat / notice-domain-page-ui
  src/main/java/org/example/ui/component/panel/NoticeHeaderPanel.java
  src/main/java/org/example/ui/component/panel/NoticeMainPanel.java
  src/main/java/org/example/ui/component/panel/NoticePanel.java
  src/main/java/org/example/ui/page/NoticePage.java
Labels: feature, client

#51 Feat/page transition navigation bar
  src/main/java/org/example/TwitterApplication.java
  src/main/java/org/example/ui/component/panel/HeaderPanel.java
  src/main/java/org/example/ui/component/panel/InteractionPanel.java
  src/main/java/org/example/ui/component/panel/NavigationPanel.java
  src/main/java/org/example/ui/component/panel/TweetPanel.java
  src/main/java/org/example/ui/page/FollowPage.java
  src/main/java/org/example/ui/page/HomeFeedPage.java
  src/main/java/org/example/ui/page/MyPage.java
  src/main/java/org/example/ui/page/NewTweetPage.java
  src/main/java/org/example/ui/page/TweetDetailPage.java
Labels: enhancement, client

#53 Refactor: customize transaction scope
  src/main/java/org/example/domain/block/repository/BlockRepository.java
  src/main/java/org/example/domain/block/service/BlockService.java
  src/main/java/org/example/domain/block/usecase/BlockUseCase.java
  src/main/java/org/example/domain/comment/repository/CommentRepository.java
  src/main/java/org/example/domain/comment/service/CommentService.java
  src/main/java/org/example/domain/comment/usecase/CommentUseCase.java
  src/main/java/org/example/domain/follow/repository/FollowRepository.java
  src/main/java/org/example/domain/follow/service/FollowService.java
  src/main/java/org/example/domain/follow/usecase/FollowUseCase.java
  src/main/java/org/example/domain/like/repository/CommentLikeRepository.java
  src/main/java/org/example/domain/like/repository/LikeRepository.java
  src/main/java/org/example/domain/like/repository/PostLikeRepository.java
  src/main/java/org/example/domain/like/service/CommentLikeService.java
  src/main/java/org/example/domain/like/service/LikeService.java
  src/main/java/org/example/domain/like/service/PostLikeService.java
  src/main/java/org/example/domain/like/usecase/CommentLikeUseCase.java
  src/main/java/org/example/domain/like/usecase/PostLikeUseCase.java
  src/main/java/org/example/domain/notice/repository/NoticeRepository.java
  src/main/java/org/example/domain/notice/service/NoticeService.java
  src/main/java/org/example/domain/user/repository/UserRepository.java
  src/main/java/org/example/domain/user/service/UserService.java
  src/main/java/org/example/domain/user/usecase/UserUseCase.java
  src/main/java/org/example/util/TransactionManager.java
  src/main/java/org/example/util/config/JdbcConfig.java
Labels: refactor, server

#54 feat / notice-domain-page-ui
  src/main/java/org/example/ui/page/ChangePasswordPage.java
  src/main/java/org/example/ui/page/SignUpPage.java
Labels: feature, client

#52 feat/social-page-ui
  src/main/java/org/example/ui/component/panel/FeedPanel.java
  src/main/java/org/example/ui/page/FollowPage.java
  src/main/java/org/example/ui/page/SignUpPage.java
Labels: feature, client

#58 fix: resolve conflict hyeonseo
  src/main/java/org/example/ui/page/FollowPage.java
  src/main/java/org/example/ui/page/SignUpPage.java
Labels: feature, client

#59 Feat: connect API
  src/main/java/org/example/TwitterApplication.java
  src/main/java/org/example/domain/post/repository/PostRepository.java
  src/main/java/org/example/domain/post/service/PostService.java
  src/main/java/org/example/domain/post/usecase/PostUseCase.java
  src/main/java/org/example/ui/component/label/InteractionLabel.java
  src/main/java/org/example/ui/component/panel/FeedPanel.java
  src/main/java/org/example/ui/component/panel/InteractionPanel.java
  src/main/java/org/example/ui/component/panel/NavigationPanel.java
  src/main/java/org/example/ui/component/panel/TweetPanel.java
  src/main/java/org/example/ui/page/ChangePasswordPage.java
  src/main/java/org/example/ui/page/FindPage.java
  src/main/java/org/example/ui/page/FollowPage.java
  src/main/java/org/example/ui/page/HomeFeedPage.java
  src/main/java/org/example/ui/page/LoginPage.java
  src/main/java/org/example/ui/page/MainFrame.java
  src/main/java/org/example/ui/page/MyPage.java
  src/main/java/org/example/ui/page/NewTweetPage.java
  src/main/java/org/example/ui/page/NoticePage.java
  src/main/java/org/example/ui/page/SignUpPage.java
  src/main/java/org/example/ui/page/TweetDetailPage.java
  src/main/java/org/example/ui/page/UpdateMemberInformationPage.java
Labels: feature, client

#60 fix: resolve conflict
  src/main/java/org/example/ui/page/FollowPage.java
Labels: feature, client

#61 fix: resolve conflict
  src/main/java/org/example/ui/page/FollowPage.java
  src/main/java/org/example/ui/page/SignUpPage.java
Labels: feature, client

#62 feat - notice-domain-page-ui
  src/main/java/org/example/ui/component/panel/MyPageHeaderPanel.java
  src/main/java/org/example/ui/component/panel/UpdateHeaderPanel.java
  src/main/java/org/example/ui/page/LoginPage.java
  src/main/java/org/example/ui/page/MainFrame.java
  src/main/java/org/example/ui/page/UpdateMemberInformationPage.java
Labels: feature, client
